-- begin EDMS_OUTGOING_DOCUMENT
alter table EDMS_OUTGOING_DOCUMENT add constraint FK_EDMS_OUTGOING_DOCUMENT_ON_DOCUMENT_TYPE foreign key (DOCUMENT_TYPE_ID) references EDMS_DOCUMENT_TYPE(ID)^
alter table EDMS_OUTGOING_DOCUMENT add constraint FK_EDMS_OUTGOING_DOCUMENT_ON_DESTINATION foreign key (DESTINATION_ID) references EDMS_ORGANIZATION(ID)^
alter table EDMS_OUTGOING_DOCUMENT add constraint FK_EDMS_OUTGOING_DOCUMENT_ON_EXECUTOR foreign key (EXECUTOR_ID) references EDMS_WORKER(ID)^
alter table EDMS_OUTGOING_DOCUMENT add constraint FK_EDMS_OUTGOING_DOCUMENT_ON_SIGNER foreign key (SIGNER_ID) references EDMS_WORKER(ID)^
alter table EDMS_OUTGOING_DOCUMENT add constraint FK_EDMS_OUTGOING_DOCUMENT_ON_AUTHOR foreign key (AUTHOR_ID) references SEC_USER(ID)^
alter table EDMS_OUTGOING_DOCUMENT add constraint FK_EDMS_OUTGOING_DOCUMENT_ON_LOGBOOK foreign key (LOGBOOK_ID) references EDMS_LOGBOOK(ID)^
alter table EDMS_OUTGOING_DOCUMENT add constraint FK_EDMS_OUTGOING_DOCUMENT_ON_ACT foreign key (ACT_ID) references EDMS_NOMENCLATURE(ID)^
alter table EDMS_OUTGOING_DOCUMENT add constraint FK_EDMS_OUTGOING_DOCUMENT_ON_RECONCILING foreign key (RECONCILING_ID) references EDMS_WORKER(ID)^
create index IDX_EDMS_OUTGOING_DOCUMENT_ON_DOCUMENT_TYPE on EDMS_OUTGOING_DOCUMENT (DOCUMENT_TYPE_ID)^
create index IDX_EDMS_OUTGOING_DOCUMENT_ON_DESTINATION on EDMS_OUTGOING_DOCUMENT (DESTINATION_ID)^
create index IDX_EDMS_OUTGOING_DOCUMENT_ON_EXECUTOR on EDMS_OUTGOING_DOCUMENT (EXECUTOR_ID)^
create index IDX_EDMS_OUTGOING_DOCUMENT_ON_SIGNER on EDMS_OUTGOING_DOCUMENT (SIGNER_ID)^
create index IDX_EDMS_OUTGOING_DOCUMENT_ON_AUTHOR on EDMS_OUTGOING_DOCUMENT (AUTHOR_ID)^
create index IDX_EDMS_OUTGOING_DOCUMENT_ON_LOGBOOK on EDMS_OUTGOING_DOCUMENT (LOGBOOK_ID)^
create index IDX_EDMS_OUTGOING_DOCUMENT_ON_ACT on EDMS_OUTGOING_DOCUMENT (ACT_ID)^
create index IDX_EDMS_OUTGOING_DOCUMENT_ON_RECONCILING on EDMS_OUTGOING_DOCUMENT (RECONCILING_ID)^
-- end EDMS_OUTGOING_DOCUMENT
-- begin EDMS_WORKER
alter table EDMS_WORKER add constraint FK_EDMS_WORKER_ON_USER foreign key (USER_ID) references SEC_USER(ID)^
alter table EDMS_WORKER add constraint FK_EDMS_WORKER_ON_DEPARTMENT foreign key (DEPARTMENT_ID) references EDMS_DEPARTMENT(ID)^
alter table EDMS_WORKER add constraint FK_EDMS_WORKER_ON_PHOTO foreign key (PHOTO_ID) references SYS_FILE(ID)^
create index IDX_EDMS_WORKER_ON_USER on EDMS_WORKER (USER_ID)^
create index IDX_EDMS_WORKER_ON_DEPARTMENT on EDMS_WORKER (DEPARTMENT_ID)^
create index IDX_EDMS_WORKER_ON_PHOTO on EDMS_WORKER (PHOTO_ID)^
-- end EDMS_WORKER
-- begin EDMS_DEPARTMENT
alter table EDMS_DEPARTMENT add constraint FK_EDMS_DEPARTMENT_ON_LEAD_DEPARTMENT foreign key (LEAD_DEPARTMENT_ID) references EDMS_DEPARTMENT(ID)^
alter table EDMS_DEPARTMENT add constraint FK_EDMS_DEPARTMENT_ON_DEPARTMENT_MANAGER foreign key (DEPARTMENT_MANAGER_ID) references EDMS_WORKER(ID)^
create index IDX_EDMS_DEPARTMENT_ON_LEAD_DEPARTMENT on EDMS_DEPARTMENT (LEAD_DEPARTMENT_ID)^
create index IDX_EDMS_DEPARTMENT_ON_DEPARTMENT_MANAGER on EDMS_DEPARTMENT (DEPARTMENT_MANAGER_ID)^
-- end EDMS_DEPARTMENT
-- begin EDMS_OUTGOING_DOCUMENT_FILE_DESCRIPTOR_LINK
alter table EDMS_OUTGOING_DOCUMENT_FILE_DESCRIPTOR_LINK add constraint FK_OUTDOCFILDES_ON_OUTGOING_DOCUMENT foreign key (OUTGOING_DOCUMENT_ID) references EDMS_OUTGOING_DOCUMENT(ID)^
alter table EDMS_OUTGOING_DOCUMENT_FILE_DESCRIPTOR_LINK add constraint FK_OUTDOCFILDES_ON_FILE_DESCRIPTOR foreign key (FILE_DESCRIPTOR_ID) references SYS_FILE(ID)^
-- end EDMS_OUTGOING_DOCUMENT_FILE_DESCRIPTOR_LINK
