alter table EDMS_OUTGOING_DOCUMENT add constraint FK_EDMS_OUTGOING_DOCUMENT_ON_ACT foreign key (ACT_ID) references EDMS_NOMENCLATURE(ID);
create index IDX_EDMS_OUTGOING_DOCUMENT_ON_ACT on EDMS_OUTGOING_DOCUMENT (ACT_ID);
